title: 100 Days of Code
author: adrianlavery
email: adrianlavery@microsoft.com
description: > # this means to ignore newlines until "baseurl:"
  I'm going to talk about all things code :boom:

# social links
twitter_username: @alavery2004
github_username:  @adrianlavery

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
